<?php
/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class SexoThrift
{
    const MASCULINO = 0;

    const FEMININO = 1;

    const AMBOS = 2;

    const NAO_INFORMADO = 3;

    static public $__names = array(
        0 => 'MASCULINO',
        1 => 'FEMININO',
        2 => 'AMBOS',
        3 => 'NAO_INFORMADO',
    );
}

