<?php
namespace br\gov\saude\esusab\ras\vacinacao;

/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class VacinaRowThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'imunobiologico',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'estrategiaVacinacao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        3 => array(
            'var' => 'dose',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        4 => array(
            'var' => 'lote',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'fabricante',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'grupoAtendimento',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        7 => array(
            'var' => 'stRegistroAnterior',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        8 => array(
            'var' => 'dataRegistroAnterior',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        9 => array(
            'var' => 'stAplicadoExterior',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        10 => array(
            'var' => 'uuidRnds',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        11 => array(
            'var' => 'cboPrescritorCodigo2002',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        12 => array(
            'var' => 'cid10MotivoIndicacao',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        13 => array(
            'var' => 'stPesquisaClinica',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        14 => array(
            'var' => 'anvisaProtocoloEstudo',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        15 => array(
            'var' => 'anvisaProtocoloVersao',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        16 => array(
            'var' => 'anvisaNumeroRegistro',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        17 => array(
            'var' => 'viaAdministracao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        18 => array(
            'var' => 'localAplicacao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        19 => array(
            'var' => 'coRndsFabricante',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $imunobiologico = null;
    /**
     * @var int
     */
    public $estrategiaVacinacao = null;
    /**
     * @var int
     */
    public $dose = null;
    /**
     * @var string
     */
    public $lote = null;
    /**
     * @var string
     */
    public $fabricante = null;
    /**
     * @var int
     */
    public $grupoAtendimento = null;
    /**
     * @var bool
     */
    public $stRegistroAnterior = null;
    /**
     * @var int
     */
    public $dataRegistroAnterior = null;
    /**
     * @var bool
     */
    public $stAplicadoExterior = null;
    /**
     * @var string
     */
    public $uuidRnds = null;
    /**
     * @var string
     */
    public $cboPrescritorCodigo2002 = null;
    /**
     * @var string
     */
    public $cid10MotivoIndicacao = null;
    /**
     * @var bool
     */
    public $stPesquisaClinica = null;
    /**
     * @var string
     */
    public $anvisaProtocoloEstudo = null;
    /**
     * @var string
     */
    public $anvisaProtocoloVersao = null;
    /**
     * @var string
     */
    public $anvisaNumeroRegistro = null;
    /**
     * @var int
     */
    public $viaAdministracao = null;
    /**
     * @var int
     */
    public $localAplicacao = null;
    /**
     * @var string
     */
    public $coRndsFabricante = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['imunobiologico'])) {
                $this->imunobiologico = $vals['imunobiologico'];
            }
            if (isset($vals['estrategiaVacinacao'])) {
                $this->estrategiaVacinacao = $vals['estrategiaVacinacao'];
            }
            if (isset($vals['dose'])) {
                $this->dose = $vals['dose'];
            }
            if (isset($vals['lote'])) {
                $this->lote = $vals['lote'];
            }
            if (isset($vals['fabricante'])) {
                $this->fabricante = $vals['fabricante'];
            }
            if (isset($vals['grupoAtendimento'])) {
                $this->grupoAtendimento = $vals['grupoAtendimento'];
            }
            if (isset($vals['stRegistroAnterior'])) {
                $this->stRegistroAnterior = $vals['stRegistroAnterior'];
            }
            if (isset($vals['dataRegistroAnterior'])) {
                $this->dataRegistroAnterior = $vals['dataRegistroAnterior'];
            }
            if (isset($vals['stAplicadoExterior'])) {
                $this->stAplicadoExterior = $vals['stAplicadoExterior'];
            }
            if (isset($vals['uuidRnds'])) {
                $this->uuidRnds = $vals['uuidRnds'];
            }
            if (isset($vals['cboPrescritorCodigo2002'])) {
                $this->cboPrescritorCodigo2002 = $vals['cboPrescritorCodigo2002'];
            }
            if (isset($vals['cid10MotivoIndicacao'])) {
                $this->cid10MotivoIndicacao = $vals['cid10MotivoIndicacao'];
            }
            if (isset($vals['stPesquisaClinica'])) {
                $this->stPesquisaClinica = $vals['stPesquisaClinica'];
            }
            if (isset($vals['anvisaProtocoloEstudo'])) {
                $this->anvisaProtocoloEstudo = $vals['anvisaProtocoloEstudo'];
            }
            if (isset($vals['anvisaProtocoloVersao'])) {
                $this->anvisaProtocoloVersao = $vals['anvisaProtocoloVersao'];
            }
            if (isset($vals['anvisaNumeroRegistro'])) {
                $this->anvisaNumeroRegistro = $vals['anvisaNumeroRegistro'];
            }
            if (isset($vals['viaAdministracao'])) {
                $this->viaAdministracao = $vals['viaAdministracao'];
            }
            if (isset($vals['localAplicacao'])) {
                $this->localAplicacao = $vals['localAplicacao'];
            }
            if (isset($vals['coRndsFabricante'])) {
                $this->coRndsFabricante = $vals['coRndsFabricante'];
            }
        }
    }

    public function getName()
    {
        return 'VacinaRowThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->imunobiologico);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->estrategiaVacinacao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dose);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->lote);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->fabricante);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->grupoAtendimento);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->stRegistroAnterior);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dataRegistroAnterior);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->stAplicadoExterior);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->uuidRnds);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->cboPrescritorCodigo2002);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->cid10MotivoIndicacao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->stPesquisaClinica);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 14:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->anvisaProtocoloEstudo);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 15:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->anvisaProtocoloVersao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 16:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->anvisaNumeroRegistro);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 17:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->viaAdministracao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 18:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->localAplicacao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 19:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->coRndsFabricante);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('VacinaRowThrift');
        if ($this->imunobiologico !== null) {
            $xfer += $output->writeFieldBegin('imunobiologico', TType::I64, 1);
            $xfer += $output->writeI64($this->imunobiologico);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->estrategiaVacinacao !== null) {
            $xfer += $output->writeFieldBegin('estrategiaVacinacao', TType::I64, 2);
            $xfer += $output->writeI64($this->estrategiaVacinacao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dose !== null) {
            $xfer += $output->writeFieldBegin('dose', TType::I64, 3);
            $xfer += $output->writeI64($this->dose);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->lote !== null) {
            $xfer += $output->writeFieldBegin('lote', TType::STRING, 4);
            $xfer += $output->writeString($this->lote);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->fabricante !== null) {
            $xfer += $output->writeFieldBegin('fabricante', TType::STRING, 5);
            $xfer += $output->writeString($this->fabricante);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->grupoAtendimento !== null) {
            $xfer += $output->writeFieldBegin('grupoAtendimento', TType::I64, 6);
            $xfer += $output->writeI64($this->grupoAtendimento);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->stRegistroAnterior !== null) {
            $xfer += $output->writeFieldBegin('stRegistroAnterior', TType::BOOL, 7);
            $xfer += $output->writeBool($this->stRegistroAnterior);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dataRegistroAnterior !== null) {
            $xfer += $output->writeFieldBegin('dataRegistroAnterior', TType::I64, 8);
            $xfer += $output->writeI64($this->dataRegistroAnterior);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->stAplicadoExterior !== null) {
            $xfer += $output->writeFieldBegin('stAplicadoExterior', TType::BOOL, 9);
            $xfer += $output->writeBool($this->stAplicadoExterior);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->uuidRnds !== null) {
            $xfer += $output->writeFieldBegin('uuidRnds', TType::STRING, 10);
            $xfer += $output->writeString($this->uuidRnds);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->cboPrescritorCodigo2002 !== null) {
            $xfer += $output->writeFieldBegin('cboPrescritorCodigo2002', TType::STRING, 11);
            $xfer += $output->writeString($this->cboPrescritorCodigo2002);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->cid10MotivoIndicacao !== null) {
            $xfer += $output->writeFieldBegin('cid10MotivoIndicacao', TType::STRING, 12);
            $xfer += $output->writeString($this->cid10MotivoIndicacao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->stPesquisaClinica !== null) {
            $xfer += $output->writeFieldBegin('stPesquisaClinica', TType::BOOL, 13);
            $xfer += $output->writeBool($this->stPesquisaClinica);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->anvisaProtocoloEstudo !== null) {
            $xfer += $output->writeFieldBegin('anvisaProtocoloEstudo', TType::STRING, 14);
            $xfer += $output->writeString($this->anvisaProtocoloEstudo);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->anvisaProtocoloVersao !== null) {
            $xfer += $output->writeFieldBegin('anvisaProtocoloVersao', TType::STRING, 15);
            $xfer += $output->writeString($this->anvisaProtocoloVersao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->anvisaNumeroRegistro !== null) {
            $xfer += $output->writeFieldBegin('anvisaNumeroRegistro', TType::STRING, 16);
            $xfer += $output->writeString($this->anvisaNumeroRegistro);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->viaAdministracao !== null) {
            $xfer += $output->writeFieldBegin('viaAdministracao', TType::I64, 17);
            $xfer += $output->writeI64($this->viaAdministracao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->localAplicacao !== null) {
            $xfer += $output->writeFieldBegin('localAplicacao', TType::I64, 18);
            $xfer += $output->writeI64($this->localAplicacao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->coRndsFabricante !== null) {
            $xfer += $output->writeFieldBegin('coRndsFabricante', TType::STRING, 19);
            $xfer += $output->writeString($this->coRndsFabricante);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
