<?php
namespace br\gov\saude\esusab\ras\cadastroindividual;

/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class InformacoesSocioEconomicasThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'alimentosAcabaramAntesTerDinheiroComprarMais',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'comeuAlgunsAlimentosQueTinhaDinheiroAcabou',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var bool
     */
    public $alimentosAcabaramAntesTerDinheiroComprarMais = null;
    /**
     * @var bool
     */
    public $comeuAlgunsAlimentosQueTinhaDinheiroAcabou = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['alimentosAcabaramAntesTerDinheiroComprarMais'])) {
                $this->alimentosAcabaramAntesTerDinheiroComprarMais = $vals['alimentosAcabaramAntesTerDinheiroComprarMais'];
            }
            if (isset($vals['comeuAlgunsAlimentosQueTinhaDinheiroAcabou'])) {
                $this->comeuAlgunsAlimentosQueTinhaDinheiroAcabou = $vals['comeuAlgunsAlimentosQueTinhaDinheiroAcabou'];
            }
        }
    }

    public function getName()
    {
        return 'InformacoesSocioEconomicasThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->alimentosAcabaramAntesTerDinheiroComprarMais);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->comeuAlgunsAlimentosQueTinhaDinheiroAcabou);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('InformacoesSocioEconomicasThrift');
        if ($this->alimentosAcabaramAntesTerDinheiroComprarMais !== null) {
            $xfer += $output->writeFieldBegin('alimentosAcabaramAntesTerDinheiroComprarMais', TType::BOOL, 1);
            $xfer += $output->writeBool($this->alimentosAcabaramAntesTerDinheiroComprarMais);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->comeuAlgunsAlimentosQueTinhaDinheiroAcabou !== null) {
            $xfer += $output->writeFieldBegin('comeuAlgunsAlimentosQueTinhaDinheiroAcabou', TType::BOOL, 2);
            $xfer += $output->writeBool($this->comeuAlgunsAlimentosQueTinhaDinheiroAcabou);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
