<?php
namespace br\gov\saude\esusab\ras\common;

/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ResultadosExameThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'exame',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'dataSolicitacao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        3 => array(
            'var' => 'dataRealizacao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        4 => array(
            'var' => 'dataResultado',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        6 => array(
            'var' => 'resultadoExame',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\br\gov\saude\esusab\ras\common\ResultadoExameThrift',
                ),
        ),
    );

    /**
     * @var string
     */
    public $exame = null;
    /**
     * @var int
     */
    public $dataSolicitacao = null;
    /**
     * @var int
     */
    public $dataRealizacao = null;
    /**
     * @var int
     */
    public $dataResultado = null;
    /**
     * @var \br\gov\saude\esusab\ras\common\ResultadoExameThrift[]
     */
    public $resultadoExame = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['exame'])) {
                $this->exame = $vals['exame'];
            }
            if (isset($vals['dataSolicitacao'])) {
                $this->dataSolicitacao = $vals['dataSolicitacao'];
            }
            if (isset($vals['dataRealizacao'])) {
                $this->dataRealizacao = $vals['dataRealizacao'];
            }
            if (isset($vals['dataResultado'])) {
                $this->dataResultado = $vals['dataResultado'];
            }
            if (isset($vals['resultadoExame'])) {
                $this->resultadoExame = $vals['resultadoExame'];
            }
        }
    }

    public function getName()
    {
        return 'ResultadosExameThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->exame);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dataSolicitacao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dataRealizacao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dataResultado);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::LST) {
                        $this->resultadoExame = array();
                        $_size0 = 0;
                        $_etype3 = 0;
                        $xfer += $input->readListBegin($_etype3, $_size0);
                        for ($_i4 = 0; $_i4 < $_size0; ++$_i4) {
                            $elem5 = null;
                            $elem5 = new \br\gov\saude\esusab\ras\common\ResultadoExameThrift();
                            $xfer += $elem5->read($input);
                            $this->resultadoExame []= $elem5;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ResultadosExameThrift');
        if ($this->exame !== null) {
            $xfer += $output->writeFieldBegin('exame', TType::STRING, 1);
            $xfer += $output->writeString($this->exame);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dataSolicitacao !== null) {
            $xfer += $output->writeFieldBegin('dataSolicitacao', TType::I64, 2);
            $xfer += $output->writeI64($this->dataSolicitacao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dataRealizacao !== null) {
            $xfer += $output->writeFieldBegin('dataRealizacao', TType::I64, 3);
            $xfer += $output->writeI64($this->dataRealizacao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dataResultado !== null) {
            $xfer += $output->writeFieldBegin('dataResultado', TType::I64, 4);
            $xfer += $output->writeI64($this->dataResultado);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->resultadoExame !== null) {
            if (!is_array($this->resultadoExame)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('resultadoExame', TType::LST, 6);
            $output->writeListBegin(TType::STRUCT, count($this->resultadoExame));
            foreach ($this->resultadoExame as $iter6) {
                $xfer += $iter6->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
